baseURL: https://williamstead.com/
languageCode: en-us
title: Wil Stead
disablePathToLower: true

menu: main

minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: false
  tdewolff:
    css:
      decimals: -1
      keepCSS2: true
    html:
      keepConditionalComments: true
      keepDefaultAttrVals: true
      keepDocumentTags: true
      keepEndTags: true
      keepQuotes: false
      keepWhitespace: false
    js: {}
    json: {}
    svg:
      decimals: -1
    xml:
      keepWhitespace: false

deployment:
  targets:
    - name: Azure
      URL: azblob://$web