name: Build and deploy the site
on:
  push:
    branches: [ main ]
jobs:
  build-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v1
        with:
          # Semantic version range syntax or exact version of a dotnet version
          dotnet-version: '7.0.x'
          include-prerelease: true

      - name: Install dependencies
        run: dotnet restore
        working-directory: ./src

      - name: Build
        run: dotnet build --configuration Release --no-restore --nologo
        working-directory: ./src

      - name: Publish
        run: dotnet publish --configuration Release -o publish --no-build --nologo
        working-directory: ./src

      # copy index.html to 404.html to fix GitHub Pages SPA navigation
      - name: copy index.html to 404.html
        run: |
          cp index.html 404.html
        working-directory: ./src/publish/wwwroot

      # add .nojekyll file so GitHub pages will not treat this as a Jekyll project
      - name: Add .nojekyll file
        run: touch publish/wwwroot/.nojekyll
        working-directory: ./src

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: src/publish/wwwroot