name: Build and deploy the site

defaults:
    run:
        shell: bash

on:
    push:
        branches:
            - master

env:
    HUGO_VERSION: 0.74.3
    BASE_URL: https://williamstead.com
    AZURE_STORAGE_ACCOUNT: williamsteadcomstorage

jobs:
    build-deploy:
        name: Build and deploy
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2
              with:
                  fetch-depth: 1
                  clean: true
                  submodules: false
            - name: Download Hugo v${{ env.HUGO_VERSION }} Linux x64
              run: "wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb -O hugo_extended_${{ env.HUGO_VERSION }}_Linux-64bit.deb"
            - name: Install Hugo
              run: sudo dpkg -i hugo*.deb
            - name: Build
              run: hugo --baseUrl '${{ env.BASE_URL }}'
            - name: Deploy to Azure blob
              run: hugo deploy --maxDeletes -1
              env:
                  AZURE_STORAGE_ACCOUNT: ${{ env.AZURE_STORAGE_ACCOUNT }}
                  AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}